#include <stdbool.h>

#include "main.h"
#include "tle94112dorin.hpp"

// PA4 is wired to SPI_CS
STM32_Pin CS_PIN_DEF = {GPIOA, GPIO_PIN_4};

int main(void) {
    autogenerated_setup();
    
    // initialize TLE94112 here
    TLE94112 motor_driver;
    motor_driver.init(&CS_PIN_DEF);
    
    static bool emergency_stop = false;

    while (1) {
        if(HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_6) == GPIO_PIN_SET) {
            if (!emergency_stop) {
                emergency_stop = true;
                // Safely shut down the PWM signals via SPI since EN is hardwired
                motor_driver.stop();
            }
        }

        if (!emergency_stop) {
            // raise motor2 here
            motor_driver.M2.set_direction(UP);
            
            // Explicitly ensure the other motors remain stationary
            motor_driver.M1.set_direction(KEEP);
            motor_driver.M3.set_direction(KEEP);
            
            // Execute the movement (20ms pulse to raise the motor)
            // step_motors() automatically resets directions to KEEP after execution
            motor_driver.step_motors(20);
            
            // Optional: Add a delay here so it doesn't continuously 
            // hammer the motor upward in a tight loop.
            HAL_Delay(500); 
        }
        
        HAL_Delay(10); 
    }
}