#include <stdbool.h>

#include "main.h"
#include "tle94112.hpp"

STM32_Pin CS_PIN_DEF = {GPIOA, GPIO_PIN_4};

int main(void) {
    autogenerated_setup();
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);

    TLE94112 motor_driver(&CS_PIN_DEF);
    motor_driver.init();

    
    static bool emergency_stop = false;

    movement dir = UP;

    motor_driver.M2.set_direction(dir);
    
    motor_driver.M1.set_direction(KEEP);
    motor_driver.M3.set_direction(KEEP);
    
    motor_driver.step_motors(400, 8);
        
    HAL_Delay(500);         


    GPIO_PinState prev_pressed = HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_6);
    if (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_6) == GPIO_PIN_SET && prev_pressed == GPIO_PIN_RESET) {
        if (dir == UP) dir = DOWN;
        else dir = UP;
        prev_pressed = GPIO_PIN_SET;
    }
    else {
        prev_pressed = GPIO_PIN_RESET;
    }
}